#!/bin/sh
source $mountpoint/etc/options_menu/themes/scripts/setVars
script_init

sType="$sftype"
[ "$sftype" = "hvcj" ] && sType="shonen"

clearDownloads

cd "$omModSub" || exit
echo ""
echo "   _____ _                    ____                _           _         "
echo "  |_   _| |_ ___ _____ ___   |    \\ ___ _ _ _ ___| |___ ___ _| |___ ___ "
echo "    | | |   | -_|     | -_|  |  |  | . | | | |   | | . | .'| . | -_|  _|"
echo "    |_| |_|_|___|_|_|_|___|  |____/|___|_____|_|_|_|___|__,|___|___|_|  "
echo "                                                                        "
echo "								Themes by:								  "
echo "		gloone, DNA64, DefKorns, pushka, HyruleExplorer, Nysde and more	"
echo "Packaging: DefKorns"
echo "Category: User Interface Mod "
echo ""
echo "Checking available theme list"
if [ ! -e "$sType"-list.tar.gz ]; then
	wget -q --spider $themeURL/"$sType"-list.tar.gz
	if [ $? -eq 0 ]; then
		echo ""
		echo "Downloading Theme list..."
		wget $themeURL/"$sType"-list.tar.gz
	else
		$errorMsg
	fi
else
	echo ""
	echo "Unpacking theme list..."
fi
echo ""
echo "Updating theme list."
tar -xzf "$sType"-list.tar.gz && rm -f *.tar.gz

echo "Update complete."

$optionsMenu/options --commandPath $omModSubCmds/ --scriptPath $omModSubScripts --title "Themes" &
