#!/bin/sh
source $mountpoint/etc/options_menu/themes/scripts/om_vars
script_init

clearList

mv "$enableClear" "$disableClear"

$optionsMenu/options --commandPath $omModCommands/ --scriptPath $omModScripts --title "Theme Selector" &
