#!/bin/sh
source $mountpoint/etc/options_menu/themes/scripts/om_vars
script_init

if [ ! -f "$subDummy" ]; then
downloader
fi
$optionsMenu/options --commandPath $omModSubCmds/ --scriptPath $omModSubScripts --title "Theme Selector" &
