#!/bin/sh
source $mountpoint/etc/options_menu/themes/scripts/setVars
script_init

# sType="$sftype"
# [ "$sftype" = "hvcj" ] && sType="shonen"

clearList

cd "$themePath" && find . -mindepth 1 -maxdepth 1 -type d | xargs -n 1 basename | sort -u | while IFS= read -r theme; do
	fullPath="$themePath/$theme"
	xtraStuff="$fullPath/xtras"
	resourcesPath="$fullPath/resources"
	spriteDir="$resourcesPath/sprites"
	scriptsPath="$resourcesPath/scripts"
	cmdList="$omModCommands/c0010_$theme"
	themeScript="$omModScripts/$theme"

	sed -r "s/CHANGE_ME/${theme}/g;" "$optionsDir/scripts/themescript" >"$themeScript"
	[ -f "$cmdList" ] && rm "$cmdList"
	touch "$cmdList"

	if [ "$sftype" = "nes" ]; then
		rename "$spriteDir/hvc.png" "$spriteDir/nes.png"
		rename "$spriteDir/hvc.json" "$spriteDir/nes.json"
		rename "$scriptsPath/colors_hvc.lua" "$scriptsPath/colors_nes.lua"
	elif [ "$sftype" = "hvc" ]; then
		rename "$spriteDir/nes.png" "$spriteDir/hvc.png"
		rename "$spriteDir/nes.json" "$spriteDir/hvc.json"
		rename "$scriptsPath/colors_nes.lua" "$scriptsPath/colors_hvc.lua"
	fi

	if [ "$theme" = "$sfregion" ]; then
		echo "#!/bin/sh
source /etc/preinit
script_init
rm $preinitpath/b8024_themeselector
rm $preinitpath/p8024_themeselector
sleep 1 
hakchi reboot" >"$themeScript.sh"
	else
		echo "#!/bin/sh
source /etc/preinit
script_init" >"$themeScript.sh"
		if [ -f "$xtraStuff/thumb.png" ]; then
			echo "sh $xtraStuff/thumbnail.sh" >>"$themeScript.sh"
		else
			echo "sh $xtraStuff/thumbnailfix.sh" >>"$themeScript.sh"
		fi

		echo "sed '1,2d' $themeScript > $preinitpath/b8024_themeselector
echo themeSelector > $preinitpath/p8024_themeselector
sleep 1 
hakchi reboot" >>"$themeScript.sh"
	fi

	cmdName="$(sed -r 's/NAME=//g' <"$fullPath/info")"
	echo "COMMAND_NAME=$cmdName
COMMAND_TYPE=INTERNAL
COMMAND_STR=sh $themeScript.sh
PREVIEW_IMAGE=$fullPath.png
PREVIEW_IMAGE_X=590
PREVIEW_IMAGE_Y=248" >"$cmdList"

done
