#!/bin/bash
# shellcheck disable=SC2154,SC2038,SC2143
#  Copyright (c) 2020 DefKorns (https://defkorns.github.io/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
themeSelector() {
  local USR_SHARE="$mountpoint/usr/share"
	local ORIGINAL_THEME="$USR_SHARE/ui/$sftype-$sfregion"
	local SYSTEM_TYPE="$sftype"
	
	case "$sftype" in
	hvcj)
		ORIGINAL_THEME="$USR_SHARE/ui/hvc"
		SYSTEM_TYPE="shonen"
		;;
	nes)
		ORIGINAL_THEME="$USR_SHARE/clover-ui"
		[ "$sfregion" = "jpn" ] && SYSTEM_TYPE="hvc"
		;;
	snes)
		[ "$sfregion" = "jpn" ] && ORIGINAL_THEME="$USR_SHARE/ui/shvc"
		;;
	esac

	local THEMES_PATH="$mountpoint/media/$modname/themes/$SYSTEM_TYPE"
	[ ! -d "$THEMES_PATH" ] && THEMES_PATH="$rootfs/usr/share/themes/$SYSTEM_TYPE"
	local STATE_PATH="$mountpoint$profilepath/$modname"
	local LAST_THEME="$STATE_PATH/lastTheme"
	local ACTIVE_THEME="$STATE_PATH/activeTheme"
	local SELECTED_THEME="CHANGEME"
	local FULL_THEME_PATH="$THEMES_PATH/$SELECTED_THEME"

		echo "$SELECTED_THEME" >"$LAST_THEME"
		echo "$FULL_THEME_PATH" >"$ACTIVE_THEME"
		mountpoint -q "$ORIGINAL_THEME" && umount "$ORIGINAL_THEME"
		[ -d "$FULL_THEME_PATH" ] && mount -t overlayfs -o lowerdir="$ORIGINAL_THEME",upperdir="$FULL_THEME_PATH" overlayfs "$ORIGINAL_THEME"
}
