#!/bin/sh
#
#  Copyright (c) 2022 DefKorns (https://defkorns.github.io/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
source $mountpoint/etc/options_menu/themes/scripts/om_vars
script_init

hasSelectedOptions "$om_themeperfolder" "$enableThemePerFolder"
hasSelectedOptions "$om_themerandomizer" "$enableThemeSetting"

hasItemsToCleanUp "SystemCleanUp"

if [ -f "$b_file" ] && [ -f "$p_file" ]; then
  enable_cmds "Uninstaller"
  [ ! -f "$omModSettingsSpacer" ] && touch "$omModSettingsSpacer"
else
  disable_cmds "Uninstaller"
  [ ! -f "$enableSystemCleanUp" ] && remove "$omModSettingsSpacer"
fi

$optionsMenu/options --commandPath $omModSettingsCmds/ --scriptPath $omModSettingsScripts --title "$omTitle" &
