#!/bin/bash
# shellcheck disable=SC2154,SC2038,SC2143,SC2030,SC2031,SC2001
#  Copyright (c) 2026 DefKorns (https://defkorns.github.io/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

musicHackBind() {
  { [ -f "$1" ] && [ -f "$2" ] && [ -f "$3/bgm_boot.wav" ] && [ -f "$3/bgm_home.wav" ]; } || return 1

  if [ "$sftype" = "nes" ]; then
    [ -f "$1" ] && mount_bind "$1" "$3/bgm_boot.wav" || return 1
  else
    [ -f "$silent_wav" ] && mount_bind "$silent_wav" "$3/bgm_boot.wav" || return 1
  fi

  [ -f "$2" ] && mount_bind "$2" "$3/bgm_home.wav" || return 1
  return 0
}

unbindThemeMounts() {
  local mount_points
  mount_points="$(awk -v dir="$original_theme/" 'index($5, dir) == 1 && ($4 ~ /\/themes\// || $4 ~ /^\/diy_theme\// || $4 ~ /\/music_menu\//) { print $5 }' /proc/self/mountinfo | sed -n '1!G;h;$p')"
  [ -n "$mount_points" ] && echo "$mount_points" | xargs umount
}

fontBindFix() {
  [ ! -f "${font_path}/title.fnt.backup" ] && cp "${font_path}/title.fnt" "${font_path}/title.fnt.backup"
  for font_name in title s m l small medium large; do
    if [ "$1" == "backup" ] && [ -f "$full_theme_path/fonts/${font_name}.fnt" ]; then
      cp "$full_theme_path/fonts/${font_name}.fnt" "${font_path}/${font_name}.fnt"
    elif [ "$font_name" == "title" ]; then
      cp "${font_path}/title.fnt.backup" "${font_path}/title.fnt"
    else
      umount "${original_theme}/resources/fonts/${ui_subdir}/${font_name}.fnt" 2>/dev/null
      rm -f "${font_path}/${font_name}.fnt"
    fi
  done
}

assignedFolderTheme() {
  local mapping_line
  [ -n "$1" ] && [ -f "$theme_state_path/folder_themes" ] || return 1
  while IFS= read -r mapping_line; do
    if [ "${mapping_line%=*}" = "$1" ] && [ -d "$themes_path/${mapping_line##*=}" ]; then
      echo "${mapping_line##*=}"
      return 0
    fi
  done <"$theme_state_path/folder_themes"
  return 1
}

assignedFolderMusic() {
  local mapping_line
  [ -n "$1" ] && [ -f "$theme_state_path/folder_music" ] || return 1
  while IFS= read -r mapping_line; do
    if [ "${mapping_line%=*}" = "$1" ] && [ -f "$music_path/${mapping_line##*=}" ]; then
      echo "${mapping_line##*=}"
      return 0
    fi
  done <"$theme_state_path/folder_music"
  return 1
}

folderEntry() {
  local folder_desktop
  for folder_desktop in "$game_storage"/*/CLV-S-00"$1"/CLV-S-00"$1".desktop; do
    [ -f "$folder_desktop" ] || continue
    grep -q -e '^Name=Back$' -e '^Name=Home$' "$folder_desktop" && continue
    echo "$folder_desktop"
    return 0
  done
  return 1
}

activeFolderExists() {
  local folder_desktop
  for folder_desktop in "$game_storage/$active_folder.desktop" "$game_storage/$active_folder/$active_folder.desktop" "$game_storage"/*/"$active_folder"/"$active_folder".desktop; do
    [ -f "$folder_desktop" ] && return 0
  done
  return 1
}

folderKeys() {
  local folder_code="$1"
  local folder_desktop
  local level=0
  if [ "$folder_code" == "000" ]; then
    echo "home"
    return
  fi
  while [ "$folder_code" != "000" ] && [ "$level" -lt 16 ]; do
    level=$((level + 1))
    folder_desktop="$(folderEntry "$folder_code")" || return
    awk '/^Name=/ { name = substr($0, 6); gsub(/ /, "_", name); print tolower(name); exit }' "$folder_desktop"
    folder_code="${folder_desktop%/*/*}"
    folder_code="${folder_code##*/}"
  done
}

folderTheme() {
  local folder_key
  for folder_key in $1; do
    assignedFolderTheme "$folder_key" && return 0
    [ "$folder_key" != "home" ] && [ -d "$themes_path/$folder_key" ] && echo "$folder_key" && return 0
  done
  return 1
}

folderMusic() {
  local folder_key
  for folder_key in $1; do
    assignedFolderMusic "$folder_key" && return 0
  done
  return 1
}

themeSelector() {
  local folder_id
  local game_storage
  local previous_theme
  local ui_dir="ui/$sftype-$sfregion"
  local ui_subdir=""
  local system_type="$sftype"

  case "$sftype" in
  hvcj)
    ui_dir="ui/hvc"
    system_type="shonen"
    ;;
  nes)
    ui_dir="clover-ui"
    ui_subdir="nes/"
    if [ "$sfregion" = "jpn" ]; then
      ui_dir="clover-ui"
      ui_subdir="hvc"
      system_type="$ui_subdir"
    fi
    ;;
  snes)
    [ "$sfregion" = "jpn" ] && ui_dir="ui/shvc"
    ;;
  esac
  local original_theme="$mountpoint/usr/share/$ui_dir"
  local original_theme_audio="$original_theme/resources/sounds/hvc"
  local themes_path="$mountpoint/media/$modname/themes/$system_type"
  [ ! -d "$themes_path" ] && themes_path="$rootfs/usr/share/themes/$system_type"
  local theme_state_path="$mountpoint$profilepath/$modname"
  folder_id="$(cat "$theme_state_path/menu")"
  local active_folder="CLV-S-00${folder_id}"
  local last_theme="$theme_state_path/lastTheme"
  local active_theme_file="$theme_state_path/active_theme"
  local applied_file="/tmp/om_theme_applied"
  [ -f "$last_theme" ] && previous_theme=$(cat "$last_theme")

  local selected_theme="CHANGEME"
  local diy_theme="$mountpoint/tmp/diy_theme"
  local full_theme_path="$themes_path/$selected_theme"
  local font_path="$mountpoint/media/$modname/fonts"
  [ ! -d "$font_path" ] && font_path="$rootfs/usr/share/fonts"
  local title_font="$font_path/title.fnt"
  local theme_font_path="$full_theme_path/fonts"

  local silent_wav="$rootfs/usr/share/themes/bgm_boot.wav"
  local music_path="$mountpoint/media/$modname/music_menu"
  find "$music_path" -maxdepth 1 -type f -iname "*.wav" 2>/dev/null | read -r _ || music_path="$rootfs/usr/share/music_menu"
  local bgm_home=""
  game_storage="$(findGameStorage)"

  activeFolderExists || return 0

  if [ -f "$theme_state_path/om_themerandomizer" ]; then
    local theme_dir_list
    theme_dir_list="$(find "$themes_path" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | sed 's#^.*/##')"
    selected_theme="$previous_theme"
    local n="0"
    while [ "$selected_theme" == "$previous_theme" ] && [ "$n" -lt 3 ]; do
      n=$((n + 1))
      selected_theme="$(printf '%s\n' "$theme_dir_list" | shuf | head -n1)"
    done
  fi

  [ "$folder_id" == "000" ] && [ -d "$themes_path/default" ] && selected_theme="default"
  local folder_keys=""
  if [ -f "$theme_state_path/om_themeperfolder" ] || [ -f "$theme_state_path/om_musicperfolder" ]; then
    folder_keys="$(folderKeys "$folder_id")"
  fi
  if [ -f "$theme_state_path/om_themeperfolder" ]; then
    local assigned_theme
    assigned_theme="$(folderTheme "$folder_keys")"
    [ -n "$assigned_theme" ] && selected_theme="$assigned_theme"
  fi
  local assigned_music=""
  [ -f "$theme_state_path/om_musicperfolder" ] && assigned_music="$(folderMusic "$folder_keys")"

  full_theme_path="$themes_path/$selected_theme"

  if find "$diy_theme" -type f 2>/dev/null | read -r _; then
    full_theme_path="$diy_theme"
  fi

  if [ "$selected_theme" != "$previous_theme" ] || [ ! -f "$last_theme" ] || [ ! -f "$active_theme_file" ]; then
    echo "$selected_theme" >"$last_theme"
    echo "$full_theme_path" >"$active_theme_file"
  fi

  local applied="$full_theme_path|$assigned_music"
  if [ -z "$mountpoint" ] && [ "$full_theme_path" != "$diy_theme" ] && [ -d "$full_theme_path" ] &&
    [ ! -f "$theme_state_path/om_themerandomizer" ] && [ ! -f "$theme_state_path/om_audiorandomizer" ] &&
    [ "$(cat "$applied_file" 2>/dev/null)" = "$applied" ]; then
    return 0
  fi

  if [ -d "$theme_font_path" ]; then
    cmp -s "$title_font" "$theme_font_path/title.fnt" || fontBindFix "backup"
  else
    fontBindFix "restore"
  fi

  unbindThemeMounts
  while grep -q " $original_theme overlayfs " /proc/mounts; do
    umount -l "$original_theme" || break
  done

  if [ "$full_theme_path" != "$diy_theme" ] && [ -f "$full_theme_path/needs_overlay" ]; then
    [ -d "$full_theme_path" ] && mount -t overlayfs -o lowerdir="$original_theme",upperdir="$full_theme_path" overlayfs "$original_theme"
  else
    if [ -z "$assigned_music" ] && [ -f "$theme_state_path/om_audiorandomizer" ] && [ -n "$(ls -A "$music_path")" ]; then
      [ -z "$bgm_home" ] && bgm_home="$(find "$music_path" -maxdepth 1 -type f -iname "*.wav" | shuf | head -n1)"
      if [ "$folder_id" = "000" ]; then
        musicHackBind "$bgm_home" "$bgm_home" "$original_theme_audio"
      else
        [ -f "$theme_state_path/om_advmusichack" ] && [ -z "$(find "$full_theme_path" -type f -name "*.wav")" ] && musicHackBind "$bgm_home" "$bgm_home" "$original_theme_audio"
      fi
    fi

    local skip_bgm="none"
    [ -n "$assigned_music" ] && skip_bgm="bgm_*.wav"
    find "$full_theme_path" -type f ! -path "$full_theme_path/fonts/*" ! -name "$skip_bgm" ! -name info ! -name bind_ok ! -name needs_overlay 2>/dev/null | while IFS= read -r theme_file; do
      mount -o bind "$theme_file" "$original_theme/${theme_file#"$full_theme_path"/}"
    done
  fi
  [ -n "$assigned_music" ] && musicHackBind "$music_path/$assigned_music" "$music_path/$assigned_music" "$original_theme_audio"

  [ -z "$mountpoint" ] && echo "$applied" >"$applied_file"
}
