#!/bin/bash
#
themeSelector() {
	local theme="CHANGE_ME"
	local cloverTheme="$mountpoint/usr/share/ui/$sftype-$sfregion"
	sysType="$sftype"
	local themePath="$mountpoint/media/$modname/themes/$sysType"
	statePath="$mountpoint$profilepath/$modname"
	local folderId
	folderId="$(cat "$statePath/menu")"
	local activeFolder="CLV-S-00$folderId"
	local prevTheme="none"
	local getName
	local fullPath
	local themeMatch
	local pID
	local parentName
	local hasParent
	local gStorage
	gStorage="$(findGameStorage)"
	local themeFile="$rootfs/overlaythemes"

	case "$sftype" in
	hvcj)
		cloverTheme="$mountpoint/usr/share/ui/hvc"
		sysType="shonen"
		;;
	nes)
		cloverTheme="$mountpoint/usr/share/clover-ui"
		[ "$sfregion" = "jpn" ] && sysType="hvc"
		;;
	snes)
		[ "$sfregion" = "jpn" ] && cloverTheme="$mountpoint/usr/share/ui/shvc"
		;;
	esac

	[ -f "$statePath/lastTheme" ] && prevTheme=$(cat "$statePath/lastTheme")
	[ ! -d "$themePath" ] && themePath="$rootfs/usr/share/themes/$sysType"

	local theme="$prevTheme"

	if grep -q -w "$theme" "$themeFile"; then
		fullPath="$themePath/$theme"
		echo "$theme" >"$statePath/lastTheme"
		mountpoint -q "$cloverTheme" && umount "$cloverTheme"
		[ -d "$fullPath" ] && mount -t overlayfs -o lowerdir="$cloverTheme",upperdir="$fullPath" overlayfs "$cloverTheme"
	else
		find "$gStorage" -maxdepth 3 -type f -name "$activeFolder.desktop" | sort -u | while IFS= read -r desktopFile; do
			cd "$gStorage" || exit
			for i in $(find . -type d -name "$activeFolder" | sed "s|^\./||"); do
				if [ "$(grep -L "Name=Back" "$i/$(basename "$i").desktop")" ]; then
					pID="$(dirname "$i")"
					local parentID="CLV-S-00$pID"
				fi
			done
			find "." -maxdepth 3 -type f -name "$parentID.desktop" -exec grep -L "Name=Back" {} \; >tmp
			while IFS= read -r w; do
				parentName="$(grep -F 'Name=' "$w" | sed -r 's/Name=//g;s/ /_/g' | awk '{print tolower($0)}')"
			done <tmp

			getName="$(grep -F 'Name=' "$desktopFile" | sed -r '/[Bb]ack/d;s/Name=//g;s/ /_/g' | awk '{print tolower($0)}')"
			themeMatch="$(find "$themePath" -maxdepth 1 -type d | xargs -n 1 basename | grep -w "$getName")"
			hasParent="$(find "$themePath" -maxdepth 1 -type d | xargs -n 1 basename | grep -w "$parentName")"

			if [ "$folderId" == "000" ] && [ -d "$themePath/default" ]; then
				fullPath="$themePath/default"
				echo "default" >"$statePath/lastTheme"
			elif [ -n "$themeMatch" ]; then
				fullPath="$themePath/$getName"
				echo "$getName" >"$statePath/lastTheme"
			elif [ -n "$hasParent" ]; then
				fullPath="$themePath/$parentName"
				echo "$parentName" >"$statePath/lastTheme"
			else
				fullPath="$themePath/$theme"
				echo "$theme" >"$statePath/lastTheme"
			fi
			echo "$fullPath" >"$statePath/activeTheme"

			cd "$themePath/$prevTheme" && find ./* -iname "*.wav" -type f | cut -c3- | while IFS= read -r uFile; do
				umount "$cloverTheme/$uFile"
			done

			cd "$fullPath" && find . -type f | while IFS= read -r tfile; do
				[ -n "$theme" ] && [ -f "$fullPath/$tfile" ] && mount_bind "$fullPath/$tfile" "$cloverTheme/$tfile"
			done
			cd - >/dev/null || exit
		done
	fi
}
