#!/bin/sh
# shellcheck disable=SC2034,SC2086,SC2154,SC3010,SC3046,SC3051
#  Copyright (c) 2026 DefKorns (https://defkorns.github.io/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# theme-selector's own toggle-marker helpers - kept separate from the shared
# om_functions (owned by OptionsMenu) so this hmod never overwrites it.

switchOff() {
  for item in "$@"; do
    [ -f "$item" ] && sed -r -i 's/ \[X\]//g' "$item"
  done
}

switchOn() {
  for item in "$@"; do
    [ -f "$item" ] && sed -r -i "1 s|$| [X]|" "$item"
  done
}
