#!/bin/sh
#
#  Copyright 2019 DefKorns (https://github.com/DefKorns/om_theme-selector/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
source /etc/preinit
script_init
#
modtitle="themes"
themeURL="http://hakchicloud.com/Hakchi_Themes/themes"
downloadURL="http://hakchicloud.com/Hakchi_Themes/scripts"
b_file="$mountpoint/etc/preinit.d/b8024_themeselector"
p_file="$mountpoint/etc/preinit.d/p8024_themeselector"
b_fntfix="$mountpoint/etc/preinit.d/b8025_fontfix"

# Options Menu
optionsMenu="$mountpoint/etc/options_menu"
omCommands="$optionsMenu/commands"
omScripts="$optionsMenu/scripts"
omMod="$optionsMenu/$modtitle"
omModCommands="$omMod/commands"
omModScripts="$omMod/scripts"
omModSpacer="$omModCommands/c0000_separator"
omModImgs="$omMod/images"
omModFnts="$omMod/fonts"
omModSub="$omMod/downloads"
omModSubCmds="$omModSub/commands"
omModSubScripts="$omModSub/scripts"
omModSubSpacer="$omModSubCmds/c9998_separator"
omModSettings="$omMod/settings"
omModSettingsCmds="$omModSettings/commands"
omModSettingsScripts="$omModSettings/scripts"

omDummy="$omModCommands/c0000_0000"
subDummy="$omModSubCmds/c0000_0000"

disableDownloads="$omModCommands/_download"
enableDownloads="$omModCommands/c0000_download"
disableClear="$omModCommands/_remove"
enableClear="$omModCommands/c0000_remove"
disableSettings="$omModCommands/_options"
enableSettings="$omModCommands/c0000_options"
audioSetting="$omModSettingsCmds/c0000_audiorandomizer"
themeSetting="$omModSettingsCmds/c0000_themerandomizer"

# SHARED
usb_path="$mountpoint/media/$modname"
nand_path="$rootfs/usr/share"
share_path="$mountpoint/usr/share"
ui_path="$share_path/ui"
s_type="$sftype"
root_bin="$rootfs/bin"
chmenu_dir="$root_bin/chmenu"
gStorage="$(findGameStorage)"

case "$sftype" in
hvcj)
	s_type="shonen"
	;;
nes)
	[ "$sfregion" = "jpn" ] && s_type="hvc"
	;;
esac
system="$(echo "$s_type" | awk '{print toupper($0)}')"
theme_path="$usb_path/$modtitle/$s_type"
[ ! -d "$theme_path" ] && theme_path="$nand_path/$modtitle/$s_type"
has_theme="$(ls -1 "$theme_path/$s_type".*.tar.gz 2>/dev/null | wc -l)"

noNet="echo Error while connecting to server, please check your internet connection and try again. "
noPkg="echo The package you resquested isn't available at the moment, please try again later or contact @DefKorns"

# functions
rename() {
	[ -f "$1" ] && mv "$1" "$2"
}

remove() {
	[ -f "$1" ] && rm -rf "$1"
}

link() {
	[ -f "$1" ] && ln -sf "$1" "$2"
}

copier() {
	[ -f "$1" ] && cp -r "$1" "$2"
}

clearList() {
	find "$omModCommands" "$omModScripts" -type f \
		-not -name 'om_*' -not -name 'c0000_*' \
		-not -name 'c999[0-9]_*' -not -name '_*' -print0 -exec rm {} \;
	remove "$omModSpacer"
}

clearDownloads() {
	find "$omModSubCmds" "$omModSubScripts" "$omModSub" -type f \
		-not -name 'c000[0-9]_*' -not -name 'c999[0-9]_*' \
		-not -name 'om_*' -not -name '_*' -print0 -exec rm {} \;
}

noThemesNoClear() {
	if [ ! -f "$omDummy" ]; then
		rename "$enableClear" "$disableClear"
	else
		rename "$disableClear" "$enableClear"
	fi
}

netChecker() {
	if ! nc -z 8.8.8.8 53 >/dev/null 2>&1; then
		# nc -z 8.8.8.8 53 >/dev/null 2>&1
		# if [ $? -eq 0 ]; then
		$noPkg
	else
		$noNet
	fi
}

themeLoader() {
	cd "$theme_path" && find . -mindepth 1 -maxdepth 1 -type d | xargs -n 1 basename | sort -u | while IFS= read -r thm; do
		full_path="$theme_path/$thm"
		xtras="$full_path/xtras"
		resource_path="$full_path/resources"
		sprite_path="$resource_path/sprites"
		script_path="$resource_path/scripts"
		cmd_list="$omModCommands/c0001_$thm"
		thm_script="$omModScripts/$thm"
		hadThumb="$theme_path/thumb"
		thm_title="$(echo "$thm" | sed -e 's/_/ /g' | awk '{for(i=1;i<=NF;i++){ $i=toupper(substr($i,1,1)) substr($i,2) }}1')"
		size="$(du -sh "$full_path" | cut -f1)"

		if [ ! -f "$full_path/info" ]; then
			echo "NAME=$thm_title [${size}b]" >"$full_path/info"
		fi

		if [ ! -f "$full_path.png" ]; then
			link "$omModSub/$thm.png" "$full_path.png"
		fi

		[ ! -f "$omModSpacer" ] && touch "$omModSpacer"
		sed -r "s/theme=\"CHANGEME\"/theme=\"${thm}\"/g;" "$omModScripts/om_themescript" >"$thm_script"
		remove "$cmd_list"
		touch "$cmd_list"

		if [ "$sftype" = "nes" ]; then
			rename "$sprite_path/hvc.png" "$sprite_path/nes.png"
			rename "$sprite_path/hvc.json" "$sprite_path/nes.json"
			rename "$script_path/colors_hvc.lua" "$script_path/colors_nes.lua"
		elif [ "$sftype-$sfregion" = "nes-jpn" ]; then
			rename "$sprite_path/nes.png" "$sprite_path/hvc.png"
			rename "$sprite_path/nes.json" "$sprite_path/hvc.json"
			rename "$script_path/colors_nes.lua" "$script_path/colors_hvc.lua"
		else
			echo "Nothing to see here!"
		fi

		echo "#!/bin/sh
#
#  Copyright 2019 DefKorns (https://github.com/DefKorns/om_theme-selector/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
source $mountpoint/etc/options_menu/themes/scripts/om_vars
script_init" >"$thm_script.sh"
		if [ -f "$xtras/thumb.png" ]; then
			echo "find \"$gStorage\" -path \"*_small.png*\" | while read -r file; do
copier \"\$file\" \"\$file\"_backup 
copier \"$xtras/thumb.png\" \"\$file\"
touch \"$hadThumb\"
done" >>"$thm_script.sh"
		else
			echo "if [ -f \"$hadThumb\" ]; then
sh $omModScripts/om_restorethumb
rm \"$hadThumb\" 
fi" >>"$thm_script.sh"
		fi
		echo "sed '1,2d' $thm_script > $b_file
echo themeSelector > $p_file
sleep 1
hakchi reboot" >>"$thm_script.sh"

		cmdName="$(sed -r 's/NAME=//g' <"$full_path/info")"
		echo "COMMAND_NAME=$cmdName
COMMAND_TYPE=INTERNAL
COMMAND_STR=sh $thm_script.sh
PREVIEW_IMAGE=$full_path.png
PREVIEW_IMAGE_X=590
PREVIEW_IMAGE_Y=248" >"$cmd_list"

	done
}

downloader() {
	cd "$omModSub" || exit
	echo ""
	echo "   _____ _                    ____                _           _         "
	echo "  |_   _| |_ ___ _____ ___   |    \\ ___ _ _ _ ___| |___ ___ _| |___ ___ "
	echo "    | | |   | -_|     | -_|  |  |  | . | | | |   | | . | .'| . | -_|  _|"
	echo "    |_| |_|_|___|_|_|_|___|  |____/|___|_____|_|_|_|___|__,|___|___|_|  "
	echo "                                                                        "
	echo "								Themes by:								  "
	echo "		gloone, DNA64, DefKorns, pushka, HyruleExplorer, Nysde and more	"
	echo "Packaging: DefKorns"
	echo "Category: User Interface Mod "
	echo ""
	echo "Checking available theme list"
	if [ ! -e "$s_type"-list.tar.gz ]; then
		clearDownloads
		if wget -q --spider $downloadURL/"$s_type"-list.tar.gz >/dev/null 2>&1; then
			echo ""
			echo "Downloading Theme list..."
			wget $downloadURL/"$s_type"-list.tar.gz
		else
			netChecker
		fi
	else
		echo ""
		echo "Unpacking theme list..."
	fi
	echo ""
	echo "Updating theme list."
	tar -xzf "$s_type"-list.tar.gz && rm -f *.tar.gz
	remove "$omModSubCmds/c0010_snesce-$sfregion"
	remove "$omModSubScripts/getSnes$sfregion"
	remove "$omModSub/$sfregion.png"
	touch "$subDummy"
	[ ! -f "$omModSubSpacer" ] && touch "$omModSubSpacer"
	echo "Update complete."
}

chMenu() {
	remove "$rootfs/chmenu"
	if [ "$(cksum "$chmenu_dir" | awk '{ print $1; }')" != "$(cksum "$omModScripts/om_chmenu" | awk '{ print $1; }')" ]; then
		copier "$omModScripts/om_chmenu" "$chmenu_dir"
		chmod +x "$chmenu_dir"
	fi
}

fntFix() {
	remove "$rootfs/fontfix"
	if [ "$(cksum "$b_fntfix" | awk '{ print $1; }')" != "$(cksum "$omModScripts/om_fontfix" | awk '{ print $1; }')" ]; then
		copier "$omModScripts/om_fontfix" "$b_fntfix"
	fi
}

themeGenerator() {
	echo "Packaging: DefKorns"
	echo "Category: User Interface Mod "
	echo ""
	echo "Checking selected theme files."
	echo ""
	full_title="$(grep -F 'NAME=' "$omModSubCmds/c0010_$theme_name" | sed -e 's/.*=\(.*\)\[.*/\1/')"
	full_path="$theme_path/$theme_name"
	cd "$theme_path" || exit

	if wget -q --spider "$themeURL/$system.$theme_name.tar.gz" >/dev/null 2>&1; then
		echo "Downloading..."
		wget "$themeURL/$system.$theme_name.tar.gz"
		echo ""
		echo "Installing Theme."
		link "$omModSub/$theme_name.png" "$full_path.png"
		tar -xzvf "$system.$theme_name.tar.gz" && rm -f ./*.tar.gz
		echo ""
		size="$(du -sh "$full_path" | cut -f1)"
		echo "NAME=$full_title [${size}b]" >"$full_path/info"
		echo "Installation complete."
	else
		netChecker
	fi
}
