#!/bin/sh
source /etc/preinit
script_init

modtitle="themes"
# subtitle="custom"
downloadURL="http://hakchicloud.com/Hakchi_Themes/themes"
preinitlauncher="$preinitpath/p8024_themeselectR"

# Options Menu
optionsMenu="$mountpoint/etc/options_menu"
omCommands="$optionsMenu/commands"
omScripts="$optionsMenu/scripts"
omMod="$optionsMenu/$modtitle"
omModCommands="$omMod/commands"
omModScripts="$omMod/scripts"
omModImgs="$omMod/images"
omModFnts="$omMod/fonts"
# omModSub="$omMod/$subtitle"
# omModSubCmds="$omModSub/commands"
# omModSubScripts="$omModSub/scripts"
# jpnSystem="$omMod/famicom"
# jpnSystemCmds="$jpnSystem/commands"
# jpnSystemScripts="$jpnSystem/scripts"
# jpnString="jpn_ja/strings"
# desktopDir="$jpnSystem/desktop"

#extra Vars
gStorage="$(findGameStorage)"
fntFix="$mountpoint/media/$modname/fonts"
[ ! -d "$fntFix" ] && fntFix="$rootfs/usr/share/fonts"

fntTitle="$fntFix/title"