#!/bin/sh
# shellcheck disable=SC1090,SC2039,SC2086,SC2154
#  Copyright (c) 2022 DefKorns (https://defkorns.github.io/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
source $mountpoint/etc/options_menu/themes/scripts/om_vars
script_init

decodepng "$omLoaders/saving.png" >/dev/fb0

name="diy_theme"
i=1

if [ -d "${theme_path}/${name}" ]; then
  while [ -d "${theme_path}/${name}-${i}" ]; do
    i=$((i + 1))
  done
  name="${name}-${i}"
fi

cp -R "${diyThemePath}" "${theme_path}/${name}"
remove "${diyThemePath}"

clearList
disable_cmds "Clear" "Preview" "DiY"
enable_cmds "Refresh"
remove "$omDummy"

loadThemeList -r

$optionsMenu/options --commandPath $omModGenCmds/ --scriptPath $omModGenScripts --title "$omTitle" &
