#!/bin/bash
# shellcheck disable=SC2086,SC2154,SC3046,SC3051
#
#  Copyright (c) 2026 DefKorns (https://defkorns.github.io/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# shellcheck source=/dev/null
source $mountpoint/etc/options_menu/themes/scripts/om_vars
script_init

case "$1" in
luigi)
  diy_om_sprite_path="$omModLuigi"
  diy_title="DEMO_CHARACTER_2_LUIGI"
  ;;
pole)
  diy_om_sprite_path="$omModPole"
  diy_title="DEMO_POLE"
  ;;
wall)
  diy_om_sprite_path="$omModWall"
  diy_title="BACKGROUND"
  ;;
wall_near)
  diy_om_sprite_path="$omModWallN"
  diy_title="DEMO_BACKGROUND_NEAR"
  ;;
wall_far)
  diy_om_sprite_path="$omModWallF"
  diy_title="DEMO_BACKGROUND_FAR"
  ;;
packed)
  diy_om_sprite_path="$omModPacked"
  diy_title="BASE_UI"
  ;;
mario)
  diy_om_sprite_path="$omModMario"
  diy_title="DEMO_CHARACTER_1_MARIO"
  ;;
colors)
  diy_om_sprite_path="$omModColors"
  diy_title="COLORS"
  ;;
colors_nes)
  diy_om_sprite_path="$omModColorsNes"
  diy_title="BACKGROUND_COLOR"
  ;;
packed_nes)
  diy_om_sprite_path="$omModPackedNes"
  diy_title="BASE_UI"
  ;;
sbm)
  diy_om_sprite_path="$omModSbm"
  diy_title="DEMO_CHARACTERS"
  ;;
esac

findDiyAsset "$1"

$optionsMenu/themes/theme_manager --commandPath $diy_om_sprite_path/commands/ --scriptPath $diy_om_sprite_path/scripts --title $diy_title --layout grid &
