#!/bin/sh
#
#  Copyright 2019 DefKorns (https://github.com/DefKorns/om_theme-selector/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
source $mountpoint/etc/options_menu/themes/scripts/om_vars
script_init

cd "$omModMario/assets" && find . -mindepth 1 -maxdepth 1 -type d | xargs -n 1 basename | sort -u | while IFS= read -r sprite; do
	full_path="$omModMario/assets/$sprite"
	cmd_list="$omModMario/commands/c0000_$sprite"
	sprite_script="$omModMario/scripts/$sprite"
	thm_title="$(echo "$sprite" | sed -e 's/_/ /g' | awk '{for(i=1;i<=NF;i++){$i=toupper(substr($i,1,1))substr($i,2)}}1')"
	remove "$cmd_list"
	touch "$cmd_list"

	cmdName="$thm_title"
	echo "COMMAND_NAME=$cmdName
COMMAND_TYPE=INTERNAL
COMMAND_STR=sh $sprite_script.sh
PREVIEW_IMAGE=$full_path/mario_run01.png
PREVIEW_IMAGE_X=590
PREVIEW_IMAGE_Y=248" >"$cmd_list"

done
cd "$theme_path" && find . -mindepth 1 -maxdepth 1 -type d | xargs -n 1 basename | sort -u | while IFS= read -r tema; do
	full_path="$theme_path/$tema"
	cmd_list="$omModMario/commands/c0000_$tema"
	tema_script="$omModMario/scripts/$tema"
	resource_path="$full_path/resources"
	mario_path="$resource_path/layout/asset/sprite/mario"
	thm_title="$(echo "$tema" | sed -e 's/_/ /g' | awk '{for(i=1;i<=NF;i++){$i=toupper(substr($i,1,1))substr($i,2)}}1')"

	if [ -d "$mario_path" ]; then
		remove "$cmd_list"
		touch "$cmd_list"
		cmdName="$(sed -r 's/NAME=//g' <"$full_path/info" | awk '{$NF="";sub(/[ \t]+$/,"")}1')"
		echo "COMMAND_NAME=$cmdName
COMMAND_TYPE=INTERNAL
COMMAND_STR=sh $tema_script.sh
PREVIEW_IMAGE=$mario_path/mario_run01.png
PREVIEW_IMAGE_X=590
PREVIEW_IMAGE_Y=248" >"$cmd_list"
	fi

done

$optionsMenu/options --commandPath $omModMario/commands/ --scriptPath $omModMario/scripts --title "$omTitle" &
