#!/bin/sh
# shellcheck disable=SC2086,SC2154,SC3046,SC3051
#
#  Copyright (c) 2026 DefKorns (https://defkorns.github.io/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# shellcheck source=/dev/null
source $mountpoint/etc/options_menu/themes/scripts/om_vars
script_init

"$omScripts/gen_splash" /tmp/om_splash.png THEME_PREVIEW_LOADING && decodepng /tmp/om_splash.png >/dev/fb0
if [ ! -f "$b_file" ]; then
  sed '1,2d' $omThemeScript >"$b_file"
  echo "themeSelector" >"$p_file"
fi

# chmenu/restart alone don't re-run preinit.d, so themeSelector's own
# DIY_THEME pickup (om_themescript) never re-fired - call it directly here,
# same as it'll run again at the next real boot via b_file/p_file
# shellcheck source=/dev/null
source "$b_file"
themeSelector

echo "usleep 20000; \
uistart; \
chmenu 001; \
usleep 200000; \
chmenu 000; \
/etc/init.d/S8103OptionsMenu restart " >/var/exec.flag
