#!/bin/sh
#
#  Copyright (c) 2021 DefKorns (https://defkorns.github.io/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
source $mountpoint/etc/options_menu/themes/scripts/om_vars
script_init

decodepng "$omLoaders/themepreview.png" >/dev/fb0
if [ ! -f "$b_file" ]; then
	sed '1,2d' $omThemeScript >"$b_file"
	echo "themeSelector" >"$p_file"
fi

echo "usleep 20000; \
uistart; \
chmenu 001; \
usleep 200000; \
chmenu 000; \
/etc/init.d/S8103OptionsMenu restart " >/var/exec.flag
