#!/bin/sh
#
#  Copyright (c) 2021 DefKorns (https://defkorns.github.io/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# shellcheck disable=SC2154,SC1090,SC2039,SC2086
source $mountpoint/etc/options_menu/themes/scripts/om_vars
script_init

if [ "$1" = "-amh" ]; then
  if [ ! -f "$om_advmusichack" ]; then
    audioRandomizerAll "on"
    [ ! -f "$om_audiorandomizer" ] && audioRandomizerHome "on"
  else
    audioRandomizerHome "off"
      remove "$om_advmusichack"
    switchOff "$enableAdvancedMusicHack"
  fi
else
  if [ ! -f "$om_audiorandomizer" ]; then
    audioRandomizerHome "on"
  else
    audioRandomizerHome "off"
    audioRandomizerAll "off"
  fi
fi

$optionsMenu/options --commandPath $omModSettingsCmds/ --scriptPath $omModSettingsScripts --title "$omTitle" &
