#!/bin/sh
#
#  Copyright (c) 2020 DefKorns (https://defkorns.github.io/LICENSE)
#  
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# shellcheck disable=SC2154,SC1090,SC2039,SC2086
source $mountpoint/etc/options_menu/themes/scripts/om_vars
script_init
decodepng "$loaders/loading.png" >/dev/fb0
imagePath="$optionsMenu/images"
themePath="$usb_path/$modtitle"
[ ! -d "$themePath" ] && themePath="$nand_path/$modtitle"

snes_del_arr="$omModPole $omModMario $omModLuigi $omModWall $omModWallN $omModWallF $omModPacked $omModColors $disableColor $disablePole $disableMario $disableLuigi $disablePacked $disableWall $disableWallFar $disableWallNear $imagePath/mario.png $imagePath/luigi.png $imagePath/packed.png $imagePath/pole.png $imagePath/wall*.png"

case "$sftype" in
hvcj)
remove "${themePath}/nes" "${themePath}/snes" "$disableSmb" "$disablePackedNes" "$disableColorsNes" "$omModPackedNes" "$omModSbm" "$omModColorsNes"
  ;;
nes) 
rmdir "$themePath/shonen" "$themePath/snes"
  for item in $snes_del_arr; do
    remove $item
    rmdir $item
  done

  ;;
snes)
remove "${themePath}/nes" "${themePath}/shonen" "$disableSmb" "$disablePackedNes" "$disableColorsNes" "$omModPackedNes" "$omModSbm" "$omModColorsNes" "$imagePath/packed_nes.png" "$imagePath/smb.png"
  ;;
esac
usleep 1000

 $optionsMenu/options --commandPath $omModSettingsCmds/ --scriptPath $omModSettingsScripts --title "$omTitle" &
