#!/bin/sh
#
#  Copyright 2019 DefKorns (https://github.com/DefKorns/om_theme-selector/LICENSE)
#  
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
source $mountpoint/etc/options_menu/themes/scripts/om_vars
script_init

if grep -q "om_themerandomizer=\"0\"" "$b_file"; then
	sed -r -i 's/om_themerandomizer=\"0\"/om_themerandomizer=\"1\"/g' $b_file
	sed -r -i "1 s|$| [X]|" $themeSetting
	# if grep -q "[X]" $themeSetting; then
	# 	sed -r -i 's/ \[X\]//g' $themeSetting
	# else
	# 	sed -r -i 's/om_themerandomizer=\"0\"/om_themerandomizer=\"1\"/g' $b_file
	# 	sed -r -i "1 s|$| [X]|" $themeSetting
	# fi
else
	sed -r -i 's/om_themerandomizer=\"1\"/om_themerandomizer=\"0\"/g' $b_file
	sed -r -i 's/ \[X\]//g' $themeSetting
fi

$optionsMenu/options --commandPath $omModSettingsCmds/ --scriptPath $omModSettingsScripts --title "$omTitle" &
