#!/bin/sh
# shellcheck disable=SC2154
#  Copyright (c) 2026 DefKorns (https://defkorns.github.io/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
move() {
  [ -f "$1" ] && mv "$1" "$2"
}

del() {
  [ -f "$1" ] && rm -rf "$1"
}

om_themes_scripts="$rootfs/etc/options_menu/themes/scripts"
usr="$rootfs/usr"
usr_share="$usr/share"
pre_initd="$rootfs/etc/preinit.d"

hmod_dir="$mountpoint/var/lib/hakchi/hmod"
b_file="$pre_initd/b8024_themeselector"
p_file="$pre_initd/p8024_themeselector"

# Uninstall any previous or legacy install (Theme Randomizer, Advanced Music Hack) 
ts_state="$mountpoint/$profilepath/$modname"
ts_backup="$installpath/om_ts_backup"
rm -rf "$ts_backup"
mkdir -p "$ts_backup/state"
for ts_dir in themes music_menu; do
  [ -d "$usr_share/$ts_dir" ] && mv "$usr_share/$ts_dir" "$ts_backup/"
done
for ts_file in lastTheme prevTheme active_theme folder_themes folder_music; do
  [ -f "$ts_state/$ts_file" ] && cp -p "$ts_state/$ts_file" "$ts_backup/state/"
done
for ts_unfile in "$hmod_dir/uninstall-"*andomiz* \
                 "$hmod_dir/uninstall-advanced_music_hack" \
                 "$hmod_dir/uninstall-om_theme-selector"* \
                 "$hmod_dir/uninstall-om_theme_selector"*; do
  [ -f "$ts_unfile" ] && pack_uninstall "${ts_unfile##*/uninstall-}"
done
cd "$transferpath" || return 1
for ts_dir in themes music_menu; do
  [ -d "$ts_backup/$ts_dir" ] && rm -rf "${usr_share:?}/$ts_dir" && mv "$ts_backup/$ts_dir" "$usr_share/"
done
mkdir -p "$ts_state"
for ts_file in "$ts_backup/state/"*; do
  [ -f "$ts_file" ] && cp -p "$ts_file" "$ts_state/"
done
rm -rf "$ts_backup"

mkdir -p "$usr_share/music_menu"
move "$usr_share/menu_music"/* "$usr_share/music_menu"
move "$usr_share/advanced_music_hack/bgm_boot.wav" "$usr_share/themes/bgm_boot.wav"
del "$pre_initd/bb223_advanced_music_hack"
del "$pre_initd/pb223_advanced_music_hack"
[ -d "$usr_share/menu_music" ] && rm -rf "$usr_share/menu_music"
[ -d "$usr_share/advanced_music_hack" ] && rm -rf "$usr_share/advanced_music_hack"
del "$pre_initd/p8024_theme_randomizR"
del "$pre_initd/b8024_theme_randomizR"
del "$rootfs/chmenu"
del "$rootfs/fontfix"
del "$rootfs/chmenu"
del "$rootfs/chmenu_backup"
del "$rootfs/b8025_fontfix_backup"
del "$ts_state/om_themeperfolderchild"

# Marks this mod as uninstalled
unset cfg_theme_randomizR_enabled

transfer_default
# saves aren't mounted yet during install - om_theme_selector resets settings on first run
om_firstrun="$rootfs/etc/options_menu/themes/om_firstrun"
[ ! -f "$om_firstrun" ] && touch "$om_firstrun"
chmod +x "$rootfs/bin/sprite_crop"
chmod +x "$rootfs/bin/theme_downloader"
chmod +x "$rootfs/etc/options_menu/lib/theme_manager"

theme_cfg="$rootfs/etc/options_menu/theme.cfg"
if [ -f "$theme_cfg" ] && ! grep -q "^ActiveThemeBorder=" "$theme_cfg"; then
  echo "ActiveThemeBorder=76,175,110" >> "$theme_cfg"
fi

sed '1,2d' "$om_themes_scripts/om_themescript" >"$b_file"
[ ! -f "$p_file" ] && echo themeSelector >"$p_file"

# shellcheck disable=SC2034
cfg_OM_ThemeSelector_enabled='y'
return 1
