#!/bin/sh
# shellcheck disable=SC2154
#  Copyright (c) 2026 DefKorns (https://defkorns.github.io/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
move() {
  [ -f "$1" ] && mv "$1" "$2"
}

del() {
  [ -f "$1" ] && rm -rf "$1"
}

# writes $om_themes_scripts/om_<name>.json by combining the console's own
# "texture" block (read live from $2, never shipped by us) with our own
# "sprites" fragment (om_<name>.sprites.json) - so the only thing this hmod
# vendors is content it actually authored, not a copy of the console's own
# sprite atlas metadata
genThemeJson() {
  [ -f "$2" ] || return
  texture="$(grep -o '"texture":[[:space:]]*{[^}]*}' "$2")"
  sprites="$(cat "$om_themes_scripts/om_${1}.sprites.json")"
  echo "{${texture},\"sprites\":${sprites}}" >"$om_themes_scripts/om_${1}.json"
}

om_themes_scripts="$rootfs/etc/options_menu/themes/scripts"
usr="$rootfs/usr"
usr_share="$usr/share"
pre_initd="$rootfs/etc/preinit.d"

hmod_dir="$mountpoint/var/lib/hakchi/hmod"
b_file="$pre_initd/b8024_themeselector"
p_file="$pre_initd/p8024_themeselector"

mkdir -p "$usr_share/music_menu"
move "$usr_share/menu_music"/* "$usr_share/music_menu"
move "$usr_share/advanced_music_hack/bgm_boot.wav" "$usr_share/themes/bgm_boot.wav"
del "$pre_initd/bb223_advanced_music_hack"
del "$pre_initd/pb223_advanced_music_hack"
[ -d "$usr_share/menu_music" ] && rm -rf "$usr_share/menu_music"
[ -d "$usr_share/advanced_music_hack" ] && rm -rf "$usr_share/advanced_music_hack"
del "$pre_initd/p8024_theme_randomizR"
del "$pre_initd/b8024_theme_randomizR"
del "$rootfs/chmenu"
del "$rootfs/fontfix"
del "$rootfs/chmenu"
del "$rootfs/chmenu_backup"
del "$rootfs/b8025_fontfix_backup"

find "$hmod_dir" -type f -name "*andomiz*" -print0 -exec rm -f {} \;
find "$hmod_dir" -type f -name "*advanced_music_hack" -print0 -exec rm -f {} \;
# Marks this mod as uninstalled
unset cfg_theme_randomizR_enabled

transfer_default
om_state_path="$mountpoint/$profilepath/$modname"
om_firstrun="$om_state_path/om_firstrun"
om_themerandomizer="$om_state_path/om_themerandomizer"
om_themeperfolder="$om_state_path/om_themeperfolder"
om_themeperfolderchild="$om_state_path/om_themeperfolderchild"
om_audiorandomizer="$om_state_path/om_audiorandomizer"
om_advmusichack="$om_state_path/om_advmusichack"
remove_settings="$om_themerandomizer $om_themeperfolder $om_themeperfolderchild $om_audiorandomizer $om_advmusichack"
[ ! -f "$om_firstrun" ] && touch "$om_firstrun"
for option in $remove_settings; do
  del "$option"
done
copy "$om_themes_scripts/om_fontfix" "$pre_initd/b8025_fontfix"
copy "$om_themes_scripts/om_chmenu" "$rootfs/bin/chmenu"
chmod +x "$rootfs/bin/chmenu"
chmod +x "$usr/bin/pngpack-upx"

sed '1,2d' "$om_themes_scripts/om_themescript" >"$b_file"
[ ! -f "$p_file" ] && echo themeSelector >"$p_file"

# regenerate the DIY sprite templates against this console's own atlas data
# (see genThemeJson above) - wall/wall_far/wall_near/packed only exist on
# SNES's UI, packed_nes is clover-ui's (NES) own equivalent
if [ "$sftype" = "snes" ]; then
  ui0="ui/$sftype-$sfregion"
  [ "$sfregion" = "jpn" ] && ui0="ui/shvc"
  wallpaper_dir="$usr_share/$ui0/resources/layout/asset/sprite/wallpaper"
  genThemeJson wall "$wallpaper_dir/wall.json"
  genThemeJson wall_far "$wallpaper_dir/wall_far.json"
  genThemeJson wall_near "$wallpaper_dir/wall_near.json"
  genThemeJson packed "$usr_share/$ui0/resources/sprites/packed.json"
elif [ "$sftype" = "nes" ]; then
  packed_nes_src="$usr_share/clover-ui/resources/sprites/nes.json"
  [ "$sfregion" = "jpn" ] && packed_nes_src="$usr_share/clover-ui/resources/sprites/hvc.json"
  genThemeJson packed_nes "$packed_nes_src"
fi

# shellcheck disable=SC2034
cfg_OM_ThemeSelector_enabled='y'
return 1
