#!/bin/sh
# shellcheck disable=SC2154,SC2068
#
#  Copyright (c) 2026 DefKorns (https://defkorns.github.io/LICENSE)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
removeItem() {
  for f in $@; do
    [ -f "$f" ] || [ -d "$f" ] && rm -rf "$f"
  done
}

font_path="$rootfs/usr/share/fonts"
ui_dir="ui/$sftype-$sfregion"
ui_subdir=""

case "$sftype" in
hvcj)
  ui_dir="ui/hvc"
  ;;
nes)
  ui_dir="clover-ui"
  ui_subdir="nes/"
  if [ "$sfregion" = "jpn" ]; then
    ui_dir="clover-ui"
    ui_subdir="hvc"
  fi
  ;;
snes)
  [ "$sfregion" = "jpn" ] && ui_dir="ui/shvc"
  ;;
esac

original_theme="$mountpoint/usr/share/$ui_dir"

sed -i '/# themeselector fix *$/,+2d' "$rootfs/bin/chmenu"
sed -i '/# themeselector$/,+4d' "$rootfs/etc/preinit.d/b8025_fontfix"
removeItem "$mountpoint/$profilepath/$modname/lastTheme"
removeItem "$mountpoint/$profilepath/$modname/prevTheme"
removeItem "$mountpoint/$profilepath/$modname/active_theme"
removeItem "$mountpoint/$profilepath/$modname/folder_themes"
removeItem "$mountpoint/$profilepath/$modname/folder_music"
removeItem "$mountpoint/$profilepath/$modname/om_advmusichack"
removeItem "$mountpoint/$profilepath/$modname/om_audiorandomizer"
removeItem "$mountpoint/$profilepath/$modname/om_themerandomizer"
removeItem "$mountpoint/$profilepath/$modname/om_firstrun"
removeItem "$rootfs/usr/share/themes"
removeItem "$rootfs/usr/share/music_menu"
chmod +x "$rootfs/bin/chmenu"
removeItem "$rootfs/etc/preinit.d/b8024_themeselector"
removeItem "$rootfs/etc/preinit.d/p8024_themeselector"
removeItem "$rootfs/etc/options_menu/commands/c0075_ThemeOptions"
removeItem "$rootfs/etc/options_menu/scripts/om_themeselector"
removeItem "$rootfs/etc/options_menu/scripts/om_theme_selector"
removeItem "$rootfs/etc/options_menu/themes"
removeItem "$rootfs/etc/options_menu/images/advanced.png"
removeItem "$rootfs/etc/options_menu/images/audio.png"
removeItem "$rootfs/etc/options_menu/images/audioall.png"
removeItem "$rootfs/etc/options_menu/images/audiohome.png"
removeItem "$rootfs/etc/options_menu/images/back.png"
removeItem "$rootfs/etc/options_menu/images/clear.png"
removeItem "$rootfs/etc/options_menu/images/colors_nes.png"
removeItem "$rootfs/etc/options_menu/images/default_preview.png"
removeItem "$rootfs/etc/options_menu/images/diy.png"
removeItem "$rootfs/etc/options_menu/images/download.png"
removeItem "$rootfs/etc/options_menu/images/exit.png"
removeItem "$rootfs/etc/options_menu/images/loading"
removeItem "$rootfs/etc/options_menu/images/luigi.png"
removeItem "$rootfs/etc/options_menu/images/mario.png"
removeItem "$rootfs/etc/options_menu/images/packed.png"
removeItem "$rootfs/etc/options_menu/images/packed_nes.png"
removeItem "$rootfs/etc/options_menu/images/pole.png"
removeItem "$rootfs/etc/options_menu/images/preview_audio_randomizer_all.png"
removeItem "$rootfs/etc/options_menu/images/preview_audio_randomizer_home.png"
removeItem "$rootfs/etc/options_menu/images/preview_clean_up.png"
removeItem "$rootfs/etc/options_menu/images/preview_diy_theme.png"
removeItem "$rootfs/etc/options_menu/images/preview_download_themes.png"
removeItem "$rootfs/etc/options_menu/images/preview_theme_options.png"
removeItem "$rootfs/etc/options_menu/images/preview_theme_randomizer.png"
removeItem "$rootfs/etc/options_menu/images/preview_update_theme_list.png"
removeItem "$rootfs/etc/options_menu/images/randtheme.png"
removeItem "$rootfs/etc/options_menu/images/retro_gaming.zip"
removeItem "$rootfs/etc/options_menu/images/retroarch.png"
removeItem "$rootfs/etc/options_menu/images/saving.png"
removeItem "$rootfs/etc/options_menu/images/sbm.png"
removeItem "$rootfs/etc/options_menu/images/settings.png"
removeItem "$rootfs/etc/options_menu/images/shutdown.png"
removeItem "$rootfs/etc/options_menu/images/themes.png"
removeItem "$rootfs/etc/options_menu/images/uninstall.png"
removeItem "$rootfs/etc/options_menu/images/update.png"
removeItem "$rootfs/etc/options_menu/images/wall.png"
removeItem "$rootfs/etc/options_menu/images/wall_far.png"
removeItem "$rootfs/etc/usr/bin/pngpack-upx"
removeItem "$rootfs/bin/sprite_crop"
removeItem "$rootfs/bin/theme_downloader"
removeItem "$rootfs/etc/options_menu/lib/theme_manager"

[ -f "${font_path}/title.fnt.backup" ] && cp "${font_path}/title.fnt.backup" "${font_path}/title.fnt"
for font_name in s m l small medium large; do
  umount "${original_theme}/resources/fonts/${ui_subdir}/${font_name}.fnt" 2>/dev/null
  rm -f "${font_path}/${font_name}.fnt"
done

unset cfg_OM_ThemeSelector_enabled
