#!/bin/sh
# shellcheck disable=SC2154,SC2068
#
#  Copyright (c) 2020 DefKorns (https://defkorns.github.io/LICENSE)
#  
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
remove() {
  for f in $@; do
    [ -f "$f" ] || [ -d "$f" ] && rm -rf "$f"
  done
}

copy "$rootfs/etc/options_menu/themes/scripts/om_chmenu_og" "$rootfs/bin/chmenu"
copy "$rootfs/etc/options_menu/themes/scripts/om_fontfix_og" "$rootfs/etc/preinit.d/b8025_fontfix"
remove "$mountpoint/$profilepath/$modname/lastTheme"
remove "$mountpoint/$profilepath/$modname/prevTheme"
remove "$mountpoint/$profilepath/$modname/activeTheme"
remove "$mountpoint/$profilepath/$modname/om_advmusichack"
remove "$mountpoint/$profilepath/$modname/om_audiorandomizer"
remove "$mountpoint/$profilepath/$modname/om_themerandomizer"
remove "$rootfs/usr/share/themes"
remove "$rootfs/usr/share/music_menu"
chmod +x "$rootfs/bin/chmenu"
remove "$rootfs/etc/preinit.d/b8024_themeselector"
remove "$rootfs/etc/preinit.d/p8024_themeselector"
remove "$rootfs/etc/options_menu/commands/c0090_ThemeOptions"
remove "$rootfs/etc/options_menu/scripts/om_themeselector"
remove "$rootfs/etc/options_menu/themes"
remove "$rootfs/etc/options_menu/images/audioall.png"
remove "$rootfs/etc/options_menu/images/audiohome.png"
remove "$rootfs/etc/options_menu/images/back.png"
remove "$rootfs/etc/options_menu/images/clear.png"
remove "$rootfs/etc/options_menu/images/colors_nes.png"
remove "$rootfs/etc/options_menu/images/default_preview.png"
remove "$rootfs/etc/options_menu/images/diy.png"
remove "$rootfs/etc/options_menu/images/download.png"
remove "$rootfs/etc/options_menu/images/loading"
remove "$rootfs/etc/options_menu/images/downloadtheme.png"
remove "$rootfs/etc/options_menu/images/downloadthemelist.png"
remove "$rootfs/etc/options_menu/images/themepreview.png"
remove "$rootfs/etc/options_menu/images/downloadtheme.png"
remove "$rootfs/etc/options_menu/images/downloadthemelist.png"
remove "$rootfs/etc/options_menu/images/loading.png"
remove "$rootfs/etc/options_menu/images/themepreview.png"
remove "$rootfs/etc/options_menu/images/loadingassets.png"
remove "$rootfs/etc/options_menu/images/luigi.png"
remove "$rootfs/etc/options_menu/images/mario.png"
remove "$rootfs/etc/options_menu/images/packed.png"
remove "$rootfs/etc/options_menu/images/packed_nes.png"
remove "$rootfs/etc/options_menu/images/pole.png"
remove "$rootfs/etc/options_menu/images/randtheme.png"
remove "$rootfs/etc/options_menu/images/retro_gaming.zip"
remove "$rootfs/etc/options_menu/images/saving.png"
remove "$rootfs/etc/options_menu/images/sbm.png"
remove "$rootfs/etc/options_menu/images/settings.png"
remove "$rootfs/etc/options_menu/images/themes.png"
remove "$rootfs/etc/options_menu/images/uninstall.png"
remove "$rootfs/etc/options_menu/images/update.png"
remove "$rootfs/etc/options_menu/images/wall.png"
remove "$rootfs/etc/options_menu/images/wall_far.png"
remove "$rootfs/etc/options_menu/images/loading"
remove "$rootfs/etc/usr/bin/pngpack-upx"

echo "COMMAND_NAME=Exit \
COMMAND_TYPE=EXTERNAL \
RESTART_UI=TRUE \
COMMAND_STR=echo \"Closing Options Menu\"
" > "$rootfs/etc/options_menu/commands/c9999_Exit"

unset cfg_OM_ThemeSelector_enabled
