#!/bin/sh
#
#  Copyright (c) 2020 DefKorns (https://defkorns.github.io/LICENSE)
#  
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
copy "$rootfs/etc/options_menu/themes/scripts/om_chmenu_og" "$rootfs/bin/chmenu"
copy "$rootfs/etc/options_menu/themes/scripts/om_fontfix_og" "$rootfs/etc/preinit.d/b8025_fontfix"
rm -fr "$mountpoint/$profilepath/$modname/lastTheme"
rm -fr "$mountpoint/$profilepath/$modname/prevTheme"
rm -fr "$mountpoint/$profilepath/$modname/activeTheme"
rm -fr "$mountpoint/$profilepath/$modname/om_advmusichack"
rm -fr "$mountpoint/$profilepath/$modname/om_audiorandomizer"
rm -fr "$mountpoint/$profilepath/$modname/om_themerandomizer"
rm -fr "$rootfs/usr/share/themes"
rm -fr "$rootfs/usr/share/music_menu"
chmod +x "$rootfs/bin/chmenu"
rm -fr "$rootfs/etc/preinit.d/b8024_themeselector"
rm -fr "$rootfs/etc/preinit.d/p8024_themeselector"
rm -fr "$rootfs/etc/options_menu/commands/c0090_ThemeOptions"
rm -fr "$rootfs/etc/options_menu/scripts/om_themeselector"
rm -fr "$rootfs/etc/options_menu/themes"
unset cfg_OM_ThemeSelector_enabled
